apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb-service
  replicas: 1  # Adjust number of replicas as needed
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest  # Use appropriate MariaDB image
          ports:
            - containerPort: 3306  # MariaDB port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Kushwaha1987
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc  # PVC name for MariaDB data storage
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306  # MariaDB port
  clusterIP: None  # Headless service for StatefulSet
